export enum AuthenticationError {
  // --- Login ---
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USER_NOT_VERIFIED = 'USER_NOT_VERIFIED',
  UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',

  // --- Registration ---
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',

  // --- Forgot Password ---
  INVALID_USER = 'INVALID_USER', // ↔ Laravel PasswordBroker::INVALID_USER
  EMAIL_SEND_FAILED = 'EMAIL_SEND_FAILED',

  // --- Reset Password ---
  INVALID_TOKEN = 'INVALID_TOKEN', // ↔ PasswordBroker::INVALID_TOKEN
  EXPIRED_TOKEN = 'EXPIRED_TOKEN',
  RESET_THROTTLED = 'RESET_THROTTLED', // ↔ PasswordBroker::RESET_THROTTLED
  RESET_ATTEMPTS_EXCEEDED = 'RESET_ATTEMPTS_EXCEEDED',
  PASSWORD_VALIDATION_FAILED = 'PASSWORD_VALIDATION_FAILED',
  RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED',

  // --- Error Umum ---
  VALIDATION_EXCEPTION = 'VALIDATION_EXCEPTION',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  DATABASE_OPERATION_FAILED = 'DATABASE_OPERATION_FAILED',
}
