<?php

namespace App\Enums\Enum;

enum AuthError: string
{
    case INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
    case USER_NOT_VERIFIED = 'USER_NOT_VERIFIED';
    case VALIDATION_ERROR = 'VALIDATION_ERROR';
    case SERVER_ERROR = 'SERVER_ERROR';
    case RESET_LINK_FAILED = 'RESET_LINK_FAILED';
}
